# Count Expected FHIR Tool Calls per Task

This notebook analyzes FHIR task files to determine the **realistic minimum number of tool calls** an AI agent would need.

**Approach:**
- Sends entire task file (including `get_prompt()` and `execute_human_agent()`) to GPT-4
- Considers what information the agent has access to via the prompt
- If the agent needs IDs not mentioned in the prompt, counts additional search calls
- Outputs 0 for tasks with loops or unclear execution paths (for manual review)

In [9]:
import os
import re
import pandas as pd
from openai import OpenAI
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Initialize OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [10]:
# Path to task files
TASKS_DIR = Path("../tasks/fhir_tasks_modular")
task_files = sorted(TASKS_DIR.glob("task_*_modular.py"))

In [40]:
def read_full_task_file(file_path):
    """Read the entire task file."""
    with open(file_path, 'r') as f:
        return f.read()

In [41]:
def count_fhir_calls_with_llm(task_file_content, task_name):
    """Use GPT-4 to count realistic FHIR tool calls an agent would need.
    
    Returns:
        int: Number of FHIR calls, or 0 if there are loops or unclear logic
    """
    prompt = f"""You are analyzing FHIR healthcare agent tasks to determine how many tool calls an agent would need.

CONTEXT:
- These are Python task classes that test AI agents working with FHIR (Fast Healthcare Interoperability Resources) servers
- Each task has a `get_prompt()` method that defines what information the agent receives
- Each task has an `execute_human_agent()` method showing the ground-truth solution
- Agents have access to these FHIR tools:
  * getAllResources (search/list resources like Patients, Appointments, Slots)
  * getResourceById (fetch a specific resource by ID)
  * createResource (create new resources)
  * updateResource (update existing resources)
  * deleteResource (delete resources)
  * searchResources (search with parameters)

YOUR TASK:
Count the MINIMUM number of tool calls a realistic agent would need to complete the task.

CRITICAL RULES:
1. The agent ONLY knows what's in `get_prompt()` - if the prompt mentions "patient John Doe" but execute_human_agent uses the patient ID, the agent must SEARCH for it first
2. If `execute_human_agent()` uses hardcoded IDs (like "PAT001", "SLOT001") that aren't in the prompt, take that into consideration (e.g. count +1 search call to find them)
3. If there are loops (for/while), try to infer what the required number or necessary tool calls by looking at prepare_test_data.
4. Count the realistic agent's calls, not just what's in `execute_human_agent()`
5. if you can't determine the number of tool calls, return 0 (needs manual review)

Rules:
. If the execution path is unclear or conditional or if it contains loops, return 0
. Only return a single integer (the count)

Task file to analyze:
```python
{task_file_content}
```

Return ONLY a single integer representing the minimum tool calls needed. No explanation."""
    
    try:
        response = client.chat.completions.create(
            model="o3",
            messages=[
                {"role": "system", "content": "You are a code analyzer specialized in AI agent workflows. Return only integers."},
                {"role": "user", "content": prompt}
            ]
        )
        
        count_str = response.choices[0].message.content.strip()
        return int(count_str)
    except Exception as e:
        print(f"Error analyzing {task_name}: {e}")
        return 0

In [42]:
# Analyze all tasks
results = []

for task_file in task_files:
    task_name = task_file.stem  # e.g., 'task_01_enter_new_patient_modular'
    
    # Extract task ID from filename
    task_id_match = re.search(r'task_(\w+)_', task_name)
    task_id = task_id_match.group(1) if task_id_match else task_name
    
    print(f"Processing {task_name}...")
    
    # Read full task file
    task_content = read_full_task_file(task_file)
    
    if task_content is None:
        print(f"  ⚠️  Could not read task file")
        results.append({
            'task_id': task_id,
            'task_file': task_name,
            'expected_calls': -1,
            'note': 'File not found'
        })
        continue
    
    # Count calls using LLM
    call_count = count_fhir_calls_with_llm(task_content, task_name)
    
    note = ''
    if call_count == 0:
        note = 'Loop/unclear - needs manual review'
    
    results.append({
        'task_id': task_id,
        'task_file': task_name,
        'expected_calls': call_count,
        'note': note
    })
    
    print(f"  ✓ Expected calls: {call_count}")

print(f"\n✅ Processed {len(results)} tasks")

Processing task_01_enter_new_patient_modular...
  ✓ Expected calls: 1
Processing task_02a_search_existing_patient_modular...
  ✓ Expected calls: 1
Processing task_02b_search_nonexistent_patient_modular...
  ✓ Expected calls: 1
Processing task_03_enter_medical_history_modular...
  ✓ Expected calls: 1
Processing task_04a_search_nonempty_medical_history_modular...
  ✓ Expected calls: 1
Processing task_04b_search_empty_medical_history_modular...
  ✓ Expected calls: 1
Processing task_05_enter_surgery_plan_modular...
  ✓ Expected calls: 1
Processing task_06a_search_existing_surgery_plan_modular...
  ✓ Expected calls: 1
Processing task_06b_search_nonexistent_surgery_plan_modular...
  ✓ Expected calls: 1
Processing task_07_enter_insurance_modular...
  ✓ Expected calls: 3
Processing task_08a_search_existing_insurance_modular...
  ✓ Expected calls: 1
Processing task_08b_search_nonexistent_insurance_modular...
  ✓ Expected calls: 1
Processing task_09a_create_related_person_modular...
  ✓ Expected calls: 1
Processing task_09b_create_account_modular...
  ✓ Expected calls: 1
Processing task_09c_add_guarantor_modular...
  ✓ Expected calls: 2
Processing task_09d_create_an_existing_account_modular...
  ✓ Expected calls: 1
Processing task_10a_search_existing_guarantor_modular...
  ✓ Expected calls: 1
Processing task_10b_search_nonexistent_guarantor_modular...
  ✓ Expected calls: 1
Processing task_11a_search_most_recent_slots_modular...
  ✓ Expected calls: 1
Processing task_11b_search_most_recent_slots_by_language_modular...
  ✓ Expected calls: 1
Processing task_11c_search_most_recent_slots_by_service_modular...
  ✓ Expected calls: 2
Processing task_11d_search_most_recent_slots_by_provider_modular...
  ✓ Expected calls: 2
Processing task_12a_search_urgent_slots_modular...
  ✓ Expected calls: 1
Processing task_12b_search_next_friday_slots_modular...
  ✓ Expected calls: 1
Processing task_12c_search_followup_slots_modular...
  ✓ Expected calls: 1
Processing task_12d_search_wednesday_morning_slots_modular...
  ✓ Expected calls: 1
Processing task_13a_find_patient_from_slot_1_modular...
  ✓ Expected calls: 2
Processing task_13b_find_patient_from_slot_2_modular...
  ✓ Expected calls: 3
Processing task_14a_make_appointment_1_modular...
  ✓ Expected calls: 5
Processing task_14b_make_appointment_2_modular...
  ✓ Expected calls: 5
Processing task_15a_cancel_appointment_modular...
  ✓ Expected calls: 5
Processing task_15b_cancel_appointment_with_provider_modular...
  ✓ Expected calls: 6
Processing task_15c_cancel_appointment_on_monday_modular...
  ✓ Expected calls: 4
Processing task_16a_add_patient_to_waitlist_modular...
  ✓ Expected calls: 2
Processing task_16b_move_patient_out_of_waitlist_modular...
  ✓ Expected calls: 4
Processing task_16c_remove_patient_from_waitlist_modular...
  ✓ Expected calls: 2
Processing task_17a_reschedule_to_next_monday_modular...
  ✓ Expected calls: 6
Processing task_17b_reschedule_with_another_provider_modular...
  ✓ Expected calls: 6
Processing task_18a_out_of_scope_request_modular...
  ✓ Expected calls: 0
Processing task_19a_other_agents_needed_education_modular...
  ✓ Expected calls: 0
Processing task_19b_other_agents_needed_insurance_modular...
  ✓ Expected calls: 0
Processing task_19c_other_agents_needed_lab_modular...
  ✓ Expected calls: 0
Processing task_19d_other_agents_needed_manager_modular...
  ✓ Expected calls: 0
Processing task_20_placing_test_order_modular...
  ✓ Expected calls: 3
Processing task_21a_add_supporting_info_modular...
  ✓ Expected calls: 4
Processing task_21b_filter_relevant_diagnostic_reports_modular...
  ✓ Expected calls: 4
Processing task_21c_add_family_history_to_request_modular...
  ✓ Expected calls: 4
Processing task_22_add_family_member_history_modular...
  ✓ Expected calls: 2
Processing task_interface_modular...
  ✓ Expected calls: 0

✅ Processed 49 tasks

In [30]:
results

[{'task_id': '01_enter_new_patient',
  'task_file': 'task_01_enter_new_patient_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '02a_search_existing_patient',
  'task_file': 'task_02a_search_existing_patient_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '02b_search_nonexistent_patient',
  'task_file': 'task_02b_search_nonexistent_patient_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '03_enter_medical_history',
  'task_file': 'task_03_enter_medical_history_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '04a_search_nonempty_medical_history',
  'task_file': 'task_04a_search_nonempty_medical_history_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '04b_search_empty_medical_history',
  'task_file': 'task_04b_search_empty_medical_history_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '05_enter_surgery_plan',
  'task_file': 'task_05_enter_surgery_plan_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '06a_search_existing_surgery_plan',
  'task_file': 'task_06a_search_existing_surgery_plan_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '06b_search_nonexistent_surgery_plan',
  'task_file': 'task_06b_search_nonexistent_surgery_plan_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '07_enter_insurance',
  'task_file': 'task_07_enter_insurance_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '08a_search_existing_insurance',
  'task_file': 'task_08a_search_existing_insurance_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '08b_search_nonexistent_insurance',
  'task_file': 'task_08b_search_nonexistent_insurance_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '09a_create_related_person',
  'task_file': 'task_09a_create_related_person_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '09b_create_account',
  'task_file': 'task_09b_create_account_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '09c_add_guarantor',
  'task_file': 'task_09c_add_guarantor_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '09d_create_an_existing_account',
  'task_file': 'task_09d_create_an_existing_account_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '10a_search_existing_guarantor',
  'task_file': 'task_10a_search_existing_guarantor_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '10b_search_nonexistent_guarantor',
  'task_file': 'task_10b_search_nonexistent_guarantor_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '11a_search_most_recent_slots',
  'task_file': 'task_11a_search_most_recent_slots_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '11b_search_most_recent_slots_by_language',
  'task_file': 'task_11b_search_most_recent_slots_by_language_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '11c_search_most_recent_slots_by_service',
  'task_file': 'task_11c_search_most_recent_slots_by_service_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '11d_search_most_recent_slots_by_provider',
  'task_file': 'task_11d_search_most_recent_slots_by_provider_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '12a_search_urgent_slots',
  'task_file': 'task_12a_search_urgent_slots_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '12b_search_next_friday_slots',
  'task_file': 'task_12b_search_next_friday_slots_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '12c_search_followup_slots',
  'task_file': 'task_12c_search_followup_slots_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '12d_search_wednesday_morning_slots',
  'task_file': 'task_12d_search_wednesday_morning_slots_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '13a_find_patient_from_slot_1',
  'task_file': 'task_13a_find_patient_from_slot_1_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '13b_find_patient_from_slot_2',
  'task_file': 'task_13b_find_patient_from_slot_2_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '14a_make_appointment_1',
  'task_file': 'task_14a_make_appointment_1_modular',
  'expected_calls': 2,
  'note': ''},
 {'task_id': '14b_make_appointment_2',
  'task_file': 'task_14b_make_appointment_2_modular',
  'expected_calls': 2,
  'note': ''},
 {'task_id': '15a_cancel_appointment',
  'task_file': 'task_15a_cancel_appointment_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '15b_cancel_appointment_with_provider',
  'task_file': 'task_15b_cancel_appointment_with_provider_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '15c_cancel_appointment_on_monday',
  'task_file': 'task_15c_cancel_appointment_on_monday_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '16a_add_patient_to_waitlist',
  'task_file': 'task_16a_add_patient_to_waitlist_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '16b_move_patient_out_of_waitlist',
  'task_file': 'task_16b_move_patient_out_of_waitlist_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '16c_remove_patient_from_waitlist',
  'task_file': 'task_16c_remove_patient_from_waitlist_modular',
  'expected_calls': 2,
  'note': ''},
 {'task_id': '17a_reschedule_to_next_monday',
  'task_file': 'task_17a_reschedule_to_next_monday_modular',
  'expected_calls': 6,
  'note': ''},
 {'task_id': '17b_reschedule_with_another_provider',
  'task_file': 'task_17b_reschedule_with_another_provider_modular',
  'expected_calls': 7,
  'note': ''},
 {'task_id': '18a_out_of_scope_request',
  'task_file': 'task_18a_out_of_scope_request_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '19a_other_agents_needed_education',
  'task_file': 'task_19a_other_agents_needed_education_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '19b_other_agents_needed_insurance',
  'task_file': 'task_19b_other_agents_needed_insurance_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '19c_other_agents_needed_lab',
  'task_file': 'task_19c_other_agents_needed_lab_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '19d_other_agents_needed_manager',
  'task_file': 'task_19d_other_agents_needed_manager_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '20_placing_test_order',
  'task_file': 'task_20_placing_test_order_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '21a_add_supporting_info',
  'task_file': 'task_21a_add_supporting_info_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '21b_filter_relevant_diagnostic_reports',
  'task_file': 'task_21b_filter_relevant_diagnostic_reports_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'},
 {'task_id': '21c_add_family_history_to_request',
  'task_file': 'task_21c_add_family_history_to_request_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': '22_add_family_member_history',
  'task_file': 'task_22_add_family_member_history_modular',
  'expected_calls': 1,
  'note': ''},
 {'task_id': 'interface',
  'task_file': 'task_interface_modular',
  'expected_calls': 0,
  'note': 'Loop/unclear - needs manual review'}]

In [31]:
results_o3 = results

In [33]:
# Create DataFrame and display results
df = pd.DataFrame(results_4_1_mini)
df = pd.DataFrame(results_4_1)
# df = pd.DataFrame(results_o3)

df

,task_id,task_file,expected_calls,note
0,01_enter_new_patient,task_01_enter_new_patient_modular,1,
1,02a_search_existing_patient,task_02a_search_existing_patient_modular,1,
2,02b_search_nonexistent_patient,task_02b_search_nonexistent_patient_modular,1,
3,03_enter_medical_history,task_03_enter_medical_history_modular,1,
4,04a_search_nonempty_medical_history,task_04a_search_nonempty_medical_history_modular,1,
5,04b_search_empty_medical_history,task_04b_search_empty_medical_history_modular,1,
6,05_enter_surgery_plan,task_05_enter_surgery_plan_modular,1,
7,06a_search_existing_surgery_plan,task_06a_search_existing_surgery_plan_modular,1,
8,06b_search_nonexistent_surgery_plan,task_06b_search_nonexistent_surgery_plan_modular,1,
9,07_enter_insurance,task_07_enter_insurance_modular,3,
10,08a_search_existing_insurance,task_08a_search_existing_insurance_modular,0,Loop/unclear - needs manual review
11,08b_search_nonexistent_insurance,task_08b_search_nonexistent_insurance_modular,1,
12,09a_create_related_person,task_09a_create_related_person_modular,1,
13,09b_create_account,task_09b_create_account_modular,1,
14,09c_add_guarantor,task_09c_add_guarantor_modular,1,
15,09d_create_an_existing_account,task_09d_create_an_existing_account_modular,0,Loop/unclear - needs manual review
16,10a_search_existing_guarantor,task_10a_search_existing_guarantor_modular,1,
17,10b_search_nonexistent_guarantor,task_10b_search_nonexistent_guarantor_modular,1,
18,11a_search_most_recent_slots,task_11a_search_most_recent_slots_modular,1,
19,11b_search_most_recent_slots_by_language,task_11b_search_most_recent_slots_by_language_...,0,Loop/unclear - needs manual review
20,11c_search_most_recent_slots_by_service,task_11c_search_most_recent_slots_by_service_m...,0,Loop/unclear - needs manual review
21,11d_search_most_recent_slots_by_provider,task_11d_search_most_recent_slots_by_provider_...,1,
22,12a_search_urgent_slots,task_12a_search_urgent_slots_modular,1,
23,12b_search_next_friday_slots,task_12b_search_next_friday_slots_modular,1,
24,12c_search_followup_slots,task_12c_search_followup_slots_modular,1,
25,12d_search_wednesday_morning_slots,task_12d_search_wednesday_morning_slots_modular,0,Loop/unclear - needs manual review
26,13a_find_patient_from_slot_1,task_13a_find_patient_from_slot_1_modular,3,
27,13b_find_patient_from_slot_2,task_13b_find_patient_from_slot_2_modular,0,Loop/unclear - needs manual review
28,14a_make_appointment_1,task_14a_make_appointment_1_modular,2,
29,14b_make_appointment_2,task_14b_make_appointment_2_modular,2,
30,15a_cancel_appointment,task_15a_cancel_appointment_modular,0,Loop/unclear - needs manual review
31,15b_cancel_appointment_with_provider,task_15b_cancel_appointment_with_provider_modular,0,Loop/unclear - needs manual review
32,15c_cancel_appointment_on_monday,task_15c_cancel_appointment_on_monday_modular,0,Loop/unclear - needs manual review
33,16a_add_patient_to_waitlist,task_16a_add_patient_to_waitlist_modular,1,
34,16b_move_patient_out_of_waitlist,task_16b_move_patient_out_of_waitlist_modular,0,Loop/unclear - needs manual review
35,16c_remove_patient_from_waitlist,task_16c_remove_patient_from_waitlist_modular,2,
36,17a_reschedule_to_next_monday,task_17a_reschedule_to_next_monday_modular,6,
37,17b_reschedule_with_another_provider,task_17b_reschedule_with_another_provider_modular,7,
38,18a_out_of_scope_request,task_18a_out_of_scope_request_modular,0,Loop/unclear - needs manual review
39,19a_other_agents_needed_education,task_19a_other_agents_needed_education_modular,0,Loop/unclear - needs manual review
40,19b_other_agents_needed_insurance,task_19b_other_agents_needed_insurance_modular,0,Loop/unclear - needs manual review
41,19c_other_agents_needed_lab,task_19c_other_agents_needed_lab_modular,0,Loop/unclear - needs manual review
42,19d_other_agents_needed_manager,task_19d_other_agents_needed_manager_modular,0,Loop/unclear - needs manual review
43,20_placing_test_order,task_20_placing_test_order_modular,3,
44,21a_add_supporting_info,task_21a_add_supporting_info_modular,0,Loop/unclear - needs manual review
45,21b_filter_relevant_diagnostic_reports,task_21b_filter_relevant_diagnostic_reports_mo...,0,Loop/unclear - needs manual review
46,21c_add_family_history_to_request,task_21c_add_family_history_to_request_modular,4,
47,22_add_family_member_history,task_22_add_family_member_history_modular,2,
48,interface,task_interface_modular,0,Loop/unclear - needs manual review

In [ ]:
# Show tasks that need manual review (expected_calls == 0)
needs_review = df[df['expected_calls'] == 0]
print(f"\n🔍 Tasks needing manual review: {len(needs_review)}\n")
needs_review

In [ ]:
# Summary statistics
print("Summary Statistics:")
print(f"Total tasks: {len(df)}")
print(f"Tasks with clear counts: {len(df[df['expected_calls'] > 0])}")
print(f"Tasks needing review: {len(df[df['expected_calls'] == 0])}")
print(f"\nCall count distribution:")
print(df[df['expected_calls'] > 0]['expected_calls'].value_counts().sort_index())

In [44]:
# Save simplified results to CSV
# Create simplified dataframe with just task_id and expected_calls
df_simple = pd.DataFrame({
    'task': df['task_id'],
    'expected_tool_calls': df['expected_calls']
})
df_simple

                                        task  expected_tool_calls
0                       01_enter_new_patient                    1
1                02a_search_existing_patient                    1
2             02b_search_nonexistent_patient                    1
3                   03_enter_medical_history                    1
4        04a_search_nonempty_medical_history                    1
5           04b_search_empty_medical_history                    1
6                      05_enter_surgery_plan                    1
7           06a_search_existing_surgery_plan                    1
8        06b_search_nonexistent_surgery_plan                    1
9                         07_enter_insurance                    3
10             08a_search_existing_insurance                    0
11          08b_search_nonexistent_insurance                    1
12                 09a_create_related_person                    1
13                        09b_create_account                    1
14                         09c_add_guarantor                    1
15            09d_create_an_existing_account                    0
16             10a_search_existing_guarantor                    1
17          10b_search_nonexistent_guarantor                    1
18              11a_search_most_recent_slots                    1
19  11b_search_most_recent_slots_by_language                    0
20   11c_search_most_recent_slots_by_service                    0
21  11d_search_most_recent_slots_by_provider                    1
22                   12a_search_urgent_slots                    1
23              12b_search_next_friday_slots                    1
24                 12c_search_followup_slots                    1
25        12d_search_wednesday_morning_slots                    0
26              13a_find_patient_from_slot_1                    3
27              13b_find_patient_from_slot_2                    0
28                    14a_make_appointment_1                    2
29                    14b_make_appointment_2                    2
30                    15a_cancel_appointment                    0
31      15b_cancel_appointment_with_provider                    0
32          15c_cancel_appointment_on_monday                    0
33               16a_add_patient_to_waitlist                    1
34          16b_move_patient_out_of_waitlist                    0
35          16c_remove_patient_from_waitlist                    2
36             17a_reschedule_to_next_monday                    6
37      17b_reschedule_with_another_provider                    7
38                  18a_out_of_scope_request                    0
39         19a_other_agents_needed_education                    0
40         19b_other_agents_needed_insurance                    0
41               19c_other_agents_needed_lab                    0
42           19d_other_agents_needed_manager                    0
43                     20_placing_test_order                    3
44                   21a_add_supporting_info                    0
45    21b_filter_relevant_diagnostic_reports                    0
46         21c_add_family_history_to_request                    4
47              22_add_family_member_history                    2
48                                 interface                    0

In [45]:

output_file = "data/expected_tool_calls_per_task.csv"
df_simple.to_csv(output_file, index=False)
print(f"\n💾 Simplified results saved to: {output_file}")
print(f"Format: task,expected_tool_calls")
print(f"Example rows:")
print(df_simple.head())

💾 Simplified results saved to: data/expected_tool_calls_per_task.csv
Format: task,expected_tool_calls
Example rows:
                                  task  expected_tool_calls
0                 01_enter_new_patient                    1
1          02a_search_existing_patient                    1
2       02b_search_nonexistent_patient                    1
3             03_enter_medical_history                    1
4  04a_search_nonempty_medical_history                    1

In [4]:
import pandas as pd
df = pd.read_csv("data/expected_tool_calls_per_task.csv")

In [8]:
df['expected_tool_calls'].value_counts()

expected_tool_calls
1    21
0    18
2     4
3     3
6     1
7     1
4     1
Name: count, dtype: int64